# Azure Tester
trigger: 
- master # Triggers when on master. Either pr or push
- ri3d # Triggers on Ri3D

variables:
  isMaster: $[or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/ri3d'))]

resources:
  containers:
  - container: wpilib2021
    image: wpilib/roborio-cross-ubuntu:2021-18.04
  - container: raspbian
    image:  wpilib/raspbian-cross-ubuntu:10-18.04
  - container: bionic
    image: wpilib/aarch64-cross-ubuntu:bionic-18.04

# Sub Builders (platform dependent)
jobs:
- job: linux
  pool:
    vmImage: 'Ubuntu-latest'
    container: bionic
  steps:
  - template: azure-init.yml
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'
  - template: azure-steps.yml

- job: roborio
  pool:
    vmImage: 'Ubuntu-latest'
  container: 'wpilib2021'
  steps:
  - template: azure-init.yml
  - template: azure-steps.yml

- job: vision
  pool:
    vmImage: 'Ubuntu-latest'
  container: 'raspbian'
  steps:
  - template: azure-init.yml
  - template: azure-steps.yml

- job: windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: azure-init.yml
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'
  - template: azure-steps.yml

- job: mac
  pool:
    vmImage: 'macOS-latest'
  steps:
  - template: azure-init.yml
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'
  - template: azure-steps.yml

# Doxygen publish
- job: doxygen
  pool:
    vmImage: 'Ubuntu-latest'
  steps:
  - task: Gradle@2
    condition: and(succeeded(), eq(variables.isMaster, 'true'))
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx4096m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'installRoborioToolchain'
      options: '-PazureBuild'
  - task: Gradle@2
    condition: and(succeeded(), eq(variables.isMaster, 'true'))
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      tasks: 'doxygen'
      options: '-PazureBuild'
  - task: PublishBuildArtifacts@1
    condition: and(succeeded(), eq(variables.isMaster, 'true'))
    inputs:
      artifactName: 'doxygen'
      pathtoPublish: build/docs/doxygen